// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehsd5Vil8RGZX-rzI8fYGRvIMVpPhkZI',
    appId: '1:168899203640:web:1c95695ef493763d2d8ccd',
    messagingSenderId: '168899203640',
    projectId: 'panasonic-15385',
    authDomain: 'panasonic-15385.firebaseapp.com',
    storageBucket: 'panasonic-15385.appspot.com',
    measurementId: 'G-120YXNCH3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4Cjt04zIIcvNb6FKLfKTXJtqmCvkdkY',
    appId: '1:168899203640:android:5cd25388044cdbe12d8ccd',
    messagingSenderId: '168899203640',
    projectId: 'panasonic-15385',
    storageBucket: 'panasonic-15385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpHBsM1kIAdKQaVkjnKEocbAMc4nmheg',
    appId: '1:168899203640:ios:4ecf5c2e90e0584e2d8ccd',
    messagingSenderId: '168899203640',
    projectId: 'panasonic-15385',
    storageBucket: 'panasonic-15385.appspot.com',
    iosClientId: '168899203640-j2qln3rvb9col5mm29fmbjq4kjlojos1.apps.googleusercontent.com',
    iosBundleId: 'com.example.panasonic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbpHBsM1kIAdKQaVkjnKEocbAMc4nmheg',
    appId: '1:168899203640:ios:5ed97e375cbb84922d8ccd',
    messagingSenderId: '168899203640',
    projectId: 'panasonic-15385',
    storageBucket: 'panasonic-15385.appspot.com',
    iosClientId: '168899203640-khb9qd3rirumn00qap6fbhjdlirko99e.apps.googleusercontent.com',
    iosBundleId: 'com.example.panasonic.RunnerTests',
  );
}
